import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "md-editor-rt/lib/style.css";
import "md-editor-rt/lib/preview.css";
import { AdminProviders } from "@/components/admin-provider";
import { GlobalConfirmModal } from "@/hooks/use-confirm";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen w-full bg-slate-50/50">
          <AdminProviders>
            <main className="flex-1 h-full overflow-y-auto p-8">
              {children}
              <GlobalConfirmModal />
            </main>
          </AdminProviders>
        </div>
      </body>
    </html>
  );
}
